@startuml "proxy"

participant Game as game #LightGreen 
participant Client as client
participant Server as server
participant Discord as discord #LightBlue

client -> server : Connect

' Handshake
game -> client : Handshake
client -> server : Forward
server -> discord : Handshake

server <-- discord : Emit Ready-Event
client <-- server : Forward
game <-- client : Emit Ready-Event

' OnAcceptedJoinRequest, OnDeclinedJoinRequest
game -> client : Wants to subscribe\nto Join-Events
client -> server : Forward
server -> discord : Subscribe to\nJoin-Events

' OnAcceptedSpectateRequest...
game -> client : Wants to subscribe\nto Spectate-Events
client -> server : Forward
server -> discord : Subscribe to\nSpectate-Events

' OnUserUpdate
game -> client : Wants to subscribe\nto UserUpdate-Event
client -> server : Forward
server -> discord : Subscribe to\nUserUpdate-Event

@enduml